export const FETCH_WORD_COUNT_REQUEST = "FETCH_WORD_COUNT_REQUEST";
export const FETCH_WORD_COUNT_SUCCESS = "FETCH_WORD_COUNT_SUCCESS";
export const FETCH_WORD_COUNT_FAILURE = "FETCH_WORD_COUNT_FAILURE";
